325 Final Project: Nathaniel Gilbert, Emile Rebillard, Thomas Sorensen, Angelina Ponce

In [1]:
import pandas as pd

In [ ]:
raw_data = pd.read_csv('C:/Users/natha/OneDrive/Documents/GitHub/DIDA_325_Final-project/csvs/raw data.csv')
drops=[0,12,20,85]
raw_data.drop(raw_data.columns[drops], axis=1, inplace=True)
# These columns were dropped because they were entirely empty.

cols_to_fill = list(range(82, 97))
raw_data.iloc[:, cols_to_fill] = raw_data.iloc[:, cols_to_fill].fillna(0)
# These columns were filled with 0s because some were empty but the documnetation said they should be 0s.

In [22]:
raw_data.to_csv('C:/Users/natha/OneDrive/Documents/GitHub/DIDA_325_Final-project/csvs/cleaned_data.csv', index=False)
raw_data.head(5)

,SCL_UNITID,SCL_NAME,SPORT_CODE,SPORT_NAME,ACADEMIC_YEAR,SCL_DIV_19,SCL_SUB_19,D1_FB_CONF_19,CONFNAME_19,SCL_HBCU,...,PUB_AWARD_15,PUB_AWARD_14,PUB_AWARD_13,PUB_AWARD_12,PUB_AWARD_11,PUB_AWARD_10,PUB_AWARD_09,PUB_AWARD_08,PUB_AWARD_07,PUB_AWARD_06
0,100654,Alabama A&M University,1,Baseball,2019,1,2,Southwestern Athletic Conf.,Southwestern Athletic Conf.,Y,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,100654,Alabama A&M University,2,Men's Basketball,2019,1,2,Southwestern Athletic Conf.,Southwestern Athletic Conf.,Y,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,100654,Alabama A&M University,4,Football,2019,1,2,Southwestern Athletic Conf.,Southwestern Athletic Conf.,Y,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,100654,Alabama A&M University,6,Men's Golf,2019,1,2,Southwestern Athletic Conf.,Southwestern Athletic Conf.,Y,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,100654,Alabama A&M University,13,Men's Tennis,2019,1,2,Southwestern Athletic Conf.,Southwestern Athletic Conf.,Y,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0

1. What is your imagined position on this dataset? Who has hired you, what are the overall goals?
Our position are Data Analysts hired by Harvard University to analyze the key drivers of Academic Performance for NCAA Division I athletes and exploring methods to enhance it. We are going to focus on the Academic Progress Rate (APR), which is a calculation based off how many athletes on a team remain academiclly elligible and with the university.
2. What is the origin of the dataset? Who recorded the data? I promise you, it wasn't a user on kaggle.
Most of the data within the NCAA dataset is not gathered by the NCAA. In fact, almost all of it is gathered by the member schools, and then shared with the NCAA. However, some of this data has been directly gathered by the NCAA.
3. Explain what all of your remaining columns represent, and whether they are text, numeric, or categorical in nature. The columns remaining are SCL_UNITID (int) which is the id for each column, SCL_NAME (character), the name for the university, Sport_Code (Cateogry) and Sport_Name (chategory) which represent the id and name of the respective sport, Academic_Year(category) the year for that row, SCL_DIV_19 (Category), and SCL_SUB_19 (Category) which represent the NCAA division and subdivision they play in. D1_FB_CONF (character) and CONFNAME (character) which are the schools football and regular conference respectivley. SL_HBCU (category) and SL_Private (category) which is a binary data that shows if a school is HBCU and if a school is private. Then there are MULTIYR_APR_RATE_1000_RAW, MULTIYR_APR_RATE_1000_CI, MULTIYR_APR_RATE_1000_OFFICIAL, RAW_OR_CI, MULTIYR_SQUAD_SIZE, MULTIYR_ELIG_RATE,MULTIYR_RET_RATE which are all numeric and represent multiyear academic stats. Then from each year from 2006-2019 there are APR_RATE_XXXX_1000	ELIG_RATE_XXXX	RET_RATE_XXX	NUM_OF_ATHLETES_XXXX which are all numeric and represent single year academic stats. Finally from 2006-2020 there are PUB_AWARD_XX which are categorical values that display if a school got an academic award from the NCAA.